services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: dmath
      POSTGRES_USER: dmath
      POSTGRES_PASSWORD: dmath
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dmath -d dmath"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
